const categories = [
  { _id: 'cat1', name: 'Phones', slug: 'phones', image: '/images/categories/phones.jpg' },
  { _id: 'cat2', name: 'Laptops', slug: 'laptops', image: '/images/categories/laptops.jpg' },
  { _id: 'cat3', name: 'Gaming', slug: 'gaming', image: '/images/categories/gaming.jpg' },
  { _id: 'cat4', name: 'Accessories', slug: 'accessories', image: '/images/categories/accessories.jpg' },
  { _id: 'cat5', name: 'Smart Watches', slug: 'smart-watches', image: '/images/categories/smart-watches.jpg' },
  { _id: 'cat6', name: 'Speakers', slug: 'speakers', image: '/images/categories/speakers.avif' },
  { _id: 'cat7', name: 'Televisions', slug: 'televisions', image: '/images/categories/televisions.jpg' },
  { _id: 'cat8', name: 'Headphones', slug: 'headphones', image: '/images/categories/headphones.jpg' },
  { _id: 'cat9', name: 'Tablets', slug: 'tablets', image: '/images/categories/tablets.jpg' },
];

const catMap = Object.fromEntries(categories.map((c) => [c.slug, { _id: c._id, name: c.name, slug: c.slug }]));

const rawProducts = [
  {
    name: 'iPhone 16 Pro Max',
    description: 'The most powerful iPhone ever. A18 Pro chip, 48MP camera system, titanium design. Experience extraordinary performance and battery life.',
    price: 1599.99,
    comparePrice: 1799.99,
    categorySlug: 'phones',
    images: ['/images/products/iphone-16-pro-max.jpg'],
    stock: 25,
    rating: 4.8,
    numReviews: 342,
    featured: true,
    specs: [
      { label: 'Chip', value: 'A18 Pro' },
      { label: 'Display', value: '6.9" Super Retina XDR' },
      { label: 'Camera', value: '48MP Main + 12MP Ultra Wide + 12MP Telephoto' },
      { label: 'Battery', value: 'Up to 33 hours video playback' },
      { label: 'Storage', value: '256GB / 512GB / 1TB' },
    ],
  },
  {
    name: 'Samsung Galaxy S25 Ultra',
    description: 'Built with Galaxy AI. The ultimate smartphone experience with S Pen, 200MP camera, and all-day battery.',
    price: 1399.99,
    comparePrice: 1599.99,
    categorySlug: 'phones',
    images: ['/images/products/samsung-galaxy-s25-ultra.jpg'],
    stock: 30,
    rating: 4.7,
    numReviews: 289,
    featured: true,
    specs: [
      { label: 'Chip', value: 'Snapdragon 8 Gen 4' },
      { label: 'Display', value: '6.8" Dynamic AMOLED 2X' },
      { label: 'Camera', value: '200MP + 50MP + 12MP + 10MP' },
      { label: 'Battery', value: '5000mAh' },
      { label: 'S Pen', value: 'Built-in' },
    ],
  },
  {
    name: 'Google Pixel 9 Pro',
    description: 'The Google AI phone. Magic Editor, Best Take, and a pro-level camera system that gets better over time.',
    price: 999.99,
    comparePrice: 0,
    categorySlug: 'phones',
    images: ['/images/products/google-pixel-9-pro.jpg'],
    stock: 40,
    rating: 4.6,
    numReviews: 178,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Tensor G4' },
      { label: 'Display', value: '6.3" LTPO OLED' },
      { label: 'Camera', value: '50MP + 48MP + 48MP' },
      { label: 'Battery', value: '4700mAh' },
      { label: 'AI Features', value: 'Magic Editor, Best Take, Circle to Search' },
    ],
  },
  {
    name: 'Samsung Galaxy S25',
    description: 'Compact flagship with Snapdragon 8 Elite chip. Stunning 6.2" Dynamic AMOLED, 50MP camera system, and seven years of updates.',
    price: 799.99,
    comparePrice: 899.99,
    categorySlug: 'phones',
    images: ['/images/products/samsung-galaxy-s25.jpg'],
    stock: 35,
    rating: 4.6,
    numReviews: 312,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Snapdragon 8 Elite' },
      { label: 'Display', value: '6.2" Dynamic AMOLED 2X 120Hz' },
      { label: 'Camera', value: '50MP + 12MP + 10MP' },
      { label: 'Battery', value: '4000mAh' },
      { label: 'RAM', value: '12GB' },
    ],
  },
  {
    name: 'Samsung Galaxy S25+',
    description: 'Bigger screen, bigger battery. 6.7" QHD+ Dynamic AMOLED, 45W charging, and Snapdragon 8 Elite performance.',
    price: 999.99,
    comparePrice: 1199.99,
    categorySlug: 'phones',
    images: ['/images/products/samsung-galaxy-s25-plus.jpg'],
    stock: 30,
    rating: 4.7,
    numReviews: 245,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Snapdragon 8 Elite' },
      { label: 'Display', value: '6.7" Dynamic AMOLED 2X QHD+ 120Hz' },
      { label: 'Camera', value: '50MP + 12MP + 10MP' },
      { label: 'Battery', value: '4900mAh' },
      { label: 'Charging', value: '45W Fast Charging' },
    ],
  },
  {
    name: 'Samsung Galaxy S25 FE',
    description: 'Flagship essentials at a smarter price. Exynos 2400, 6.7" AMOLED 120Hz, and Galaxy AI features.',
    price: 649.99,
    comparePrice: 749.99,
    categorySlug: 'phones',
    images: ['/images/products/samsung-galaxy-s25-fe.jpg'],
    stock: 45,
    rating: 4.5,
    numReviews: 178,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Exynos 2400' },
      { label: 'Display', value: '6.7" FHD+ AMOLED 120Hz' },
      { label: 'Camera', value: '50MP + 12MP + 8MP' },
      { label: 'Battery', value: '4900mAh' },
      { label: 'AI', value: 'Galaxy AI Suite' },
    ],
  },
  {
    name: 'Infinix Zero 40 5G',
    description: 'Creator-focused flagship with 108MP OIS camera, 4K 60fps video, Dimensity 8200 Ultimate, and 45W fast charging.',
    price: 299.99,
    comparePrice: 399.99,
    categorySlug: 'phones',
    images: ['/images/products/infinix-zero-40-5g.jpg'],
    stock: 50,
    rating: 4.4,
    numReviews: 134,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Dimensity 8200 Ultimate' },
      { label: 'Display', value: '6.78" AMOLED 144Hz' },
      { label: 'Camera', value: '108MP OIS + 50MP Ultra + 2MP' },
      { label: 'Battery', value: '5000mAh' },
      { label: 'Charging', value: '45W + 20W Wireless' },
    ],
  },
  {
    name: 'Infinix Note 40 Pro',
    description: 'All-round FastCharge with 70W wired and 20W wireless MagCharge. 108MP OIS camera and stunning 120Hz AMOLED display.',
    price: 229.99,
    comparePrice: 299.99,
    categorySlug: 'phones',
    images: ['/images/products/infinix-note-40-pro.jpg'],
    stock: 60,
    rating: 4.3,
    numReviews: 267,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Helio G99 Ultimate' },
      { label: 'Display', value: '6.78" AMOLED 120Hz' },
      { label: 'Camera', value: '108MP OIS + 2MP + 2MP' },
      { label: 'Battery', value: '5000mAh' },
      { label: 'Charging', value: '70W + 20W Wireless' },
    ],
  },
  {
    name: 'Infinix GT 20 Pro',
    description: 'Official gaming phone of major esports tournaments. Dimensity 8200 Ultimate, 144Hz display, and Pixelworks X5 Turbo gaming chip.',
    price: 349.99,
    comparePrice: 449.99,
    categorySlug: 'phones',
    images: ['/images/products/infinix-gt-20-pro.jpg'],
    stock: 40,
    rating: 4.5,
    numReviews: 89,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Dimensity 8200 Ultimate' },
      { label: 'Display', value: '6.78" AMOLED 144Hz' },
      { label: 'Camera', value: '108MP + 2MP + 2MP' },
      { label: 'Battery', value: '5000mAh' },
      { label: 'Gaming Chip', value: 'Pixelworks X5 Turbo' },
    ],
  },
  {
    name: 'Infinix Hot 50 Pro',
    description: 'Ultra-slim 7.4mm design with 50MP camera, 120Hz AMOLED display, and 33W fast charging. Style meets performance.',
    price: 179.99,
    comparePrice: 229.99,
    categorySlug: 'phones',
    images: ['/images/products/infinix-hot-50-pro.jpg'],
    stock: 80,
    rating: 4.2,
    numReviews: 345,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Helio G100' },
      { label: 'Display', value: '6.78" AMOLED 120Hz' },
      { label: 'Camera', value: '50MP + 2MP + 2MP' },
      { label: 'Battery', value: '5000mAh' },
      { label: 'Thickness', value: '7.4mm' },
    ],
  },
  {
    name: 'Tecno Camon 30 Premier 5G',
    description: 'Dual-chip imaging flagship with Sony CXD5622GG ISP. Four 50MP lenses, 70W Ultra Charge, and Dimensity 8200 Ultimate.',
    price: 449.99,
    comparePrice: 549.99,
    categorySlug: 'phones',
    images: ['/images/products/tecno-camon-30-premier-5g.jpg'],
    stock: 25,
    rating: 4.6,
    numReviews: 112,
    featured: true,
    specs: [
      { label: 'Chip', value: 'Dimensity 8200 Ultimate' },
      { label: 'Display', value: '6.77" AMOLED LTPO 120Hz' },
      { label: 'Camera', value: '50MP OIS + 50MP 3x + 50MP UW' },
      { label: 'Battery', value: '5000mAh' },
      { label: 'Charging', value: '70W Ultra Charge' },
    ],
  },
  {
    name: 'Tecno Phantom V Fold 2',
    description: 'Premium foldable with 7.85" LTPO AMOLED inner display, 50MP triple camera, Dimensity 9000+, and 5750mAh battery.',
    price: 1099.99,
    comparePrice: 1299.99,
    categorySlug: 'phones',
    images: ['/images/products/tecno-phantom-v-fold-2.jpg'],
    stock: 15,
    rating: 4.5,
    numReviews: 67,
    featured: true,
    specs: [
      { label: 'Chip', value: 'Dimensity 9000+' },
      { label: 'Inner Display', value: '7.85" LTPO AMOLED 120Hz' },
      { label: 'Cover Display', value: '6.42" AMOLED 120Hz' },
      { label: 'Camera', value: '50MP + 50MP + 50MP' },
      { label: 'Battery', value: '5750mAh' },
    ],
  },
  {
    name: 'Tecno Spark 30 Pro',
    description: '108MP camera, 120Hz AMOLED display, stereo Dolby Atmos speakers, and 33W fast charging at an unbeatable price.',
    price: 199.99,
    comparePrice: 249.99,
    categorySlug: 'phones',
    images: ['/images/products/tecno-spark-30-pro.jpg'],
    stock: 70,
    rating: 4.3,
    numReviews: 423,
    featured: false,
    specs: [
      { label: 'Chip', value: 'Helio G100' },
      { label: 'Display', value: '6.78" AMOLED 120Hz' },
      { label: 'Camera', value: '108MP + 2MP + 2MP' },
      { label: 'Battery', value: '5000mAh' },
      { label: 'Audio', value: 'Dolby Atmos Stereo' },
    ],
  },
  {
    name: 'MacBook Pro 16" M4 Max',
    description: 'Supercharged by M4 Max chip. Up to 24-hour battery life. Stunning Liquid Retina XDR display. The ultimate pro notebook.',
    price: 3499.99,
    comparePrice: 3999.99,
    categorySlug: 'laptops',
    images: ['/images/products/macbook-pro-16-m4-max.jpg'],
    stock: 15,
    rating: 4.9,
    numReviews: 456,
    featured: true,
    specs: [
      { label: 'Chip', value: 'Apple M4 Max' },
      { label: 'RAM', value: '48GB Unified Memory' },
      { label: 'Storage', value: '1TB SSD' },
      { label: 'Display', value: '16.2" Liquid Retina XDR' },
      { label: 'Battery', value: 'Up to 24 hours' },
    ],
  },
  {
    name: 'Dell XPS 16',
    description: 'Redesigned from the ground up. InfinityEdge display, Intel Core Ultra processors, and a stunning CNC machined aluminum chassis.',
    price: 2199.99,
    comparePrice: 2499.99,
    categorySlug: 'laptops',
    images: ['/images/products/dell-xps-16.jpg'],
    stock: 20,
    rating: 4.5,
    numReviews: 123,
    featured: false,
    specs: [
      { label: 'Processor', value: 'Intel Core Ultra 9' },
      { label: 'RAM', value: '32GB DDR5' },
      { label: 'Storage', value: '1TB SSD' },
      { label: 'Display', value: '16.3" 4K OLED' },
      { label: 'GPU', value: 'NVIDIA RTX 4070' },
    ],
  },
  {
    name: 'ASUS ROG Zephyrus G16',
    description: 'Ultra-slim gaming laptop with Nebula OLED display. Powered by AMD Ryzen 9 and NVIDIA GeForce RTX 4080.',
    price: 2599.99,
    comparePrice: 0,
    categorySlug: 'laptops',
    images: ['/images/products/asus-rog-zephyrus-g16.jpg'],
    stock: 12,
    rating: 4.6,
    numReviews: 89,
    featured: true,
    specs: [
      { label: 'Processor', value: 'AMD Ryzen 9 7940HS' },
      { label: 'GPU', value: 'NVIDIA RTX 4080' },
      { label: 'RAM', value: '32GB DDR5' },
      { label: 'Display', value: '16" 2.5K OLED 240Hz' },
      { label: 'Weight', value: '1.85 kg' },
    ],
  },
  {
    name: 'PlayStation 6 Pro',
    description: 'The next generation of gaming. 8K graphics, ray tracing, ultra-fast SSD, and a revolutionary DualSense controller.',
    price: 699.99,
    comparePrice: 799.99,
    categorySlug: 'gaming',
    images: ['/images/products/playstation-6-pro.jpg'],
    stock: 50,
    rating: 4.7,
    numReviews: 567,
    featured: true,
    specs: [
      { label: 'Resolution', value: 'Up to 8K' },
      { label: 'Storage', value: '2TB SSD' },
      { label: 'Ray Tracing', value: 'Hardware Accelerated' },
      { label: 'Controller', value: 'DualSense 2' },
      { label: 'Audio', value: 'Tempest 3D AudioTech' },
    ],
  },
  {
    name: 'Xbox Series X Elite',
    description: 'The fastest, most powerful Xbox ever. 12 teraflops of raw graphic processing power. Play thousands of games.',
    price: 649.99,
    comparePrice: 699.99,
    categorySlug: 'gaming',
    images: ['/images/products/xbox-series-x-elite.jpg'],
    stock: 35,
    rating: 4.6,
    numReviews: 412,
    featured: false,
    specs: [
      { label: 'CPU', value: 'Custom Zen 4' },
      { label: 'GPU', value: '12 TFLOPS RDNA 3' },
      { label: 'Storage', value: '2TB NVMe SSD' },
      { label: 'RAM', value: '24GB GDDR6' },
      { label: 'Max Resolution', value: '8K' },
    ],
  },
  {
    name: 'Nintendo Switch 2',
    description: 'Play anytime, anywhere. Upgraded performance, improved Joy-Con, and a vibrant 8-inch display.',
    price: 449.99,
    comparePrice: 0,
    categorySlug: 'gaming',
    images: ['/images/products/nintendo-switch-2.avif'],
    stock: 60,
    rating: 4.5,
    numReviews: 234,
    featured: false,
    specs: [
      { label: 'Display', value: '8" LCD 1080p' },
      { label: 'Storage', value: '256GB Internal' },
      { label: 'Battery', value: 'Up to 8 hours' },
      { label: 'Dock', value: '4K Output' },
      { label: 'Joy-Con', value: 'Magnetic Attachment' },
    ],
  },
  {
    name: 'AirPods Max 2',
    description: 'Completely redesigned over-ear headphones. H2 chip, adaptive audio, and best-in-class noise cancellation.',
    price: 549.99,
    comparePrice: 629.99,
    categorySlug: 'headphones',
    images: ['/images/products/airpods-max-2.jpg'],
    stock: 40,
    rating: 4.7,
    numReviews: 198,
    featured: true,
    specs: [
      { label: 'Chip', value: 'Apple H2' },
      { label: 'Noise Cancellation', value: 'Active + Adaptive Transparency' },
      { label: 'Audio', value: 'Spatial Audio with Dynamic Head Tracking' },
      { label: 'Battery', value: '30 hours' },
      { label: 'Weight', value: '385g' },
    ],
  },
  {
    name: 'Sony WH-1000XM6',
    description: 'Industry-leading noise cancellation reimagined. Exceptional sound quality with adaptive sound control.',
    price: 399.99,
    comparePrice: 449.99,
    categorySlug: 'headphones',
    images: ['/images/products/sony-wh-1000xm6.jpg'],
    stock: 45,
    rating: 4.8,
    numReviews: 312,
    featured: false,
    specs: [
      { label: 'Noise Cancellation', value: 'Dual Processor HD QN1e' },
      { label: 'Driver', value: '40mm Carbon Fiber' },
      { label: 'Codec', value: 'LDAC, AAC, SBC' },
      { label: 'Battery', value: '40 hours' },
      { label: 'Weight', value: '250g' },
    ],
  },
  {
    name: 'Bose QuietComfort Ultra',
    description: 'The worlds best noise-cancelling headphones. Immersive audio with CustomTune technology.',
    price: 429.99,
    comparePrice: 0,
    categorySlug: 'headphones',
    images: ['/images/products/bose-quietcomfort-ultra.jpg'],
    stock: 35,
    rating: 4.6,
    numReviews: 167,
    featured: false,
    specs: [
      { label: 'Noise Cancellation', value: 'CustomTune' },
      { label: 'Audio', value: 'Immersive Audio' },
      { label: 'Battery', value: '32 hours' },
      { label: 'Charging', value: 'USB-C, 15 min = 3 hours' },
      { label: 'Weight', value: '270g' },
    ],
  },
  {
    name: 'Apple Watch Ultra 3',
    description: 'The most rugged and capable Apple Watch ever. Precision dual-frequency GPS, 36-hour battery life.',
    price: 799.99,
    comparePrice: 899.99,
    categorySlug: 'smart-watches',
    images: ['/images/products/apple-watch-ultra-3.jpg'],
    stock: 30,
    rating: 4.8,
    numReviews: 234,
    featured: true,
    specs: [
      { label: 'Display', value: '49mm Sapphire Crystal' },
      { label: 'Chip', value: 'S10 SiP' },
      { label: 'Battery', value: 'Up to 36 hours' },
      { label: 'Water Resistance', value: 'WR100, EN13319' },
      { label: 'GPS', value: 'Precision Dual-Frequency' },
    ],
  },
  {
    name: 'Samsung Galaxy Watch Ultra',
    description: 'Built for extreme conditions. Titanium grade 4, 10ATM water resistance, and powerful Galaxy AI features.',
    price: 649.99,
    comparePrice: 699.99,
    categorySlug: 'smart-watches',
    images: ['/images/products/samsung-galaxy-watch-ultra.jpg'],
    stock: 25,
    rating: 4.5,
    numReviews: 145,
    featured: false,
    specs: [
      { label: 'Material', value: 'Titanium Grade 4' },
      { label: 'Display', value: '1.5" Super AMOLED' },
      { label: 'Water Resistance', value: '10ATM + IP68' },
      { label: 'Battery', value: '590mAh, Up to 60 hours' },
      { label: 'Chip', value: 'Exynos W1000' },
    ],
  },
  {
    name: 'Sonos Era 300',
    description: 'Spatial audio speaker that fills the room from every angle. Dolby Atmos support with room-tuning.',
    price: 449.99,
    comparePrice: 499.99,
    categorySlug: 'speakers',
    images: ['/images/products/sonos-era-300.avif'],
    stock: 40,
    rating: 4.7,
    numReviews: 89,
    featured: false,
    specs: [
      { label: 'Audio', value: 'Spatial Audio with Dolby Atmos' },
      { label: 'Drivers', value: '6 x Class-D Amplifiers' },
      { label: 'Connectivity', value: 'Wi-Fi 6, Bluetooth 5.2' },
      { label: 'Voice', value: 'Sonos Voice, Alexa' },
      { label: 'Multi-room', value: 'Sonos Ecosystem' },
    ],
  },
  {
    name: 'Marshall Stanmore III',
    description: 'Iconic rock voice meets modern technology. HDMI input, Bluetooth 5.3, and dynamic loudness.',
    price: 379.99,
    comparePrice: 429.99,
    categorySlug: 'speakers',
    images: ['/images/products/marshall-stanmore-iii.jpg'],
    stock: 50,
    rating: 4.5,
    numReviews: 178,
    featured: false,
    specs: [
      { label: 'Power', value: '100W RMS' },
      { label: 'Frequency', value: '45 - 20,000 Hz' },
      { label: 'Connectivity', value: 'Bluetooth 5.3, HDMI, RCA' },
      { label: 'Design', value: 'Signature Marshall Vinyl' },
      { label: 'Weight', value: '4.25 kg' },
    ],
  },
  {
    name: 'Samsung QN90D 65" Neo QLED',
    description: 'Neo Quantum HDR+ with 4K upscaling. Dolby Atmos and Object Tracking Sound for a cinema experience at home.',
    price: 1999.99,
    comparePrice: 2499.99,
    categorySlug: 'televisions',
    images: ['/images/products/samsung-qn90d-65-neo-qled.jpg'],
    stock: 10,
    rating: 4.6,
    numReviews: 234,
    featured: true,
    specs: [
      { label: 'Display', value: '65" Neo QLED 4K' },
      { label: 'Refresh Rate', value: '120Hz' },
      { label: 'HDR', value: 'Neo Quantum HDR+' },
      { label: 'Audio', value: 'Dolby Atmos, OTS+' },
      { label: 'Smart TV', value: 'Tizen OS' },
    ],
  },
  {
    name: 'LG C5 55" OLED evo',
    description: 'Self-lit OLED evo pixels for perfect black. α11 AI processor, Dolby Vision, and Dolby Atmos.',
    price: 1799.99,
    comparePrice: 2199.99,
    categorySlug: 'televisions',
    images: ['/images/products/lg-c5-55-oled-evo.jpg'],
    stock: 8,
    rating: 4.8,
    numReviews: 312,
    featured: false,
    specs: [
      { label: 'Display', value: '55" OLED evo 4K' },
      { label: 'Processor', value: 'α11 AI Processor 4K' },
      { label: 'HDR', value: 'Dolby Vision, HDR10+' },
      { label: 'Refresh Rate', value: '120Hz' },
      { label: 'Smart TV', value: 'webOS 24' },
    ],
  },
  {
    name: 'Sony Bravia 9 75" Mini LED',
    description: 'XR Cognitive Processor delivers unprecedented realism. Sound that follows the action. Stunning Mini LED backlight.',
    price: 3299.99,
    comparePrice: 3799.99,
    categorySlug: 'televisions',
    images: ['/images/products/sony-bravia-9-75-mini-led.jpg'],
    stock: 5,
    rating: 4.7,
    numReviews: 89,
    featured: true,
    specs: [
      { label: 'Display', value: '75" Mini LED 4K' },
      { label: 'Processor', value: 'XR Cognitive' },
      { label: 'HDR', value: 'XR Triluminos Pro' },
      { label: 'Audio', value: 'Acoustic Multi-Audio+' },
      { label: 'Gaming', value: 'HDMI 2.1, VRR, ALLM' },
    ],
  },
  {
    name: 'iPad Pro 13" M4',
    description: 'Ultra-light, ultra-powerful. M4 chip, Ultra Retina XDR display, and Apple Pencil Pro support. The ultimate creative canvas.',
    price: 1299.99,
    comparePrice: 1499.99,
    categorySlug: 'tablets',
    images: ['/images/products/ipad-pro-13-m4.jpg'],
    stock: 20,
    rating: 4.9,
    numReviews: 345,
    featured: true,
    specs: [
      { label: 'Chip', value: 'Apple M4' },
      { label: 'Display', value: '13" Ultra Retina XDR' },
      { label: 'Storage', value: '256GB / 512GB / 1TB / 2TB' },
      { label: 'Camera', value: '12MP Wide + 10MP Ultra Wide' },
      { label: 'Pencil', value: 'Apple Pencil Pro Support' },
    ],
  },
  {
    name: 'Samsung Galaxy Tab S10 Ultra',
    description: 'The ultimate tablet experience. 14.6" Dynamic AMOLED display, Galaxy AI, and included S Pen.',
    price: 1199.99,
    comparePrice: 1399.99,
    categorySlug: 'tablets',
    images: ['/images/products/samsung-galaxy-tab-s10-ultra.jpg'],
    stock: 15,
    rating: 4.6,
    numReviews: 156,
    featured: false,
    specs: [
      { label: 'Display', value: '14.6" Dynamic AMOLED 2X' },
      { label: 'Processor', value: 'MediaTek Dimensity 9300+' },
      { label: 'RAM', value: '12GB / 16GB' },
      { label: 'Storage', value: '256GB / 512GB / 1TB' },
      { label: 'S Pen', value: 'Included, IP68' },
    ],
  },
  {
    name: 'MagSafe Charging Stand',
    description: 'Premium 3-in-1 wireless charging station for iPhone, Apple Watch, and AirPods. Fast charging supported.',
    price: 79.99,
    comparePrice: 99.99,
    categorySlug: 'accessories',
    images: ['/images/products/magsafe-charging-stand.jpg'],
    stock: 100,
    rating: 4.4,
    numReviews: 567,
    featured: false,
    specs: [
      { label: 'Compatibility', value: 'iPhone, Apple Watch, AirPods' },
      { label: 'Power', value: '25W Total' },
      { label: 'Material', value: 'Aluminum + Silicone' },
      { label: 'Charging', value: 'MagSafe 15W' },
      { label: 'Cable', value: 'USB-C, 1.5m' },
    ],
  },
  {
    name: 'USB-C Hub Pro 12-in-1',
    description: 'Essential connectivity hub with 4K HDMI, 100W PD charging, SD card reader, and Gigabit Ethernet.',
    price: 49.99,
    comparePrice: 69.99,
    categorySlug: 'accessories',
    images: ['/images/products/usb-c-hub-pro-12-in-1.jpg'],
    stock: 150,
    rating: 4.3,
    numReviews: 890,
    featured: false,
    specs: [
      { label: 'Ports', value: '12 Total' },
      { label: 'HDMI', value: '4K@60Hz' },
      { label: 'Power Delivery', value: '100W' },
      { label: 'Data', value: 'USB 3.2 Gen 2 (10Gbps)' },
      { label: 'Ethernet', value: 'Gigabit RJ45' },
    ],
  },
];

const products = rawProducts.map((p, i) => {
  const slug = p.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  return {
    _id: `prod${i + 1}`,
    ...p,
    slug,
    images: p.images,
    category: catMap[p.categorySlug],
    createdAt: new Date(Date.now() - i * 86400000).toISOString(),
  };
});

export const mockCategories = categories;
export const mockProducts = products;
